In [15]:
from keras.models import load_model
from collections import deque   
import numpy as np
import time
import pickle
import cv2
from PIL import Image as im 
import json
from urllib.request import urlopen
import firebase_admin 
from firebase_admin import credentials,db,storage, messaging

In [16]:
# idhr appne system ke according jo mai model bhejunga uska path and pickle ka bhi
# model = load_model(r'C:\Users\hp\Downloads\data\video_model\model') 
model = load_model(r"C:\Users\neeli\Downloads\Weapon_detection.h5") 
# lb = pickle.loads(open(r"C:\Users\hp\Downloads\data\video_model\labelbinarizer.pickle", "rb").read())
# lb = pickle.loads(open(r"C:\Users\neeli\Downloads\model 1 mera wala-20240117T103926Z-001\model 1 mera wala\video_model\labelbinarizer.pickle", "rb").read())
# print(pickle.loads(open(r"C:\Users\hp\Desktop\final models rj police\model 1 mera wala\video_model\labelbinarizer.pickle"))
mean = np.array([123.68, 116.779, 103.939][::1], dtype="float32")
Queue = deque(maxlen=128)
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage

smtp_port = 587
smtp_server = "smtp.gmail.com"
cred = credentials.Certificate("credentials.json")
firebase_admin.initialize_app(cred,{"storageBucket":"rajasthanpolice-bc516.appspot.com"})
bucket = storage.bucket()
registration_token = 'ctSdcSSDSZOwPqBYoy-nBJ:APA91bHEpljSq8xxAJiTtD2IvTQS9fjhb8OvoCpFNCK6n7ljiEhpbxQRUvHNoKeK5MEgvPHWICE7iyvk8it4Uu2joxu01uT4HwyFBbkBqXqCgkEfciJ2o_kSm2FkBUMVfU8af3YOz3OE'



In [18]:
# # anomaly_label = ['Arson','Assault','Burglary','Explosion','Fighting','Normal','Road_Accident','Robbery','Shooting','Vandalism']
# anomaly_label = ['Automatic Rifle', 'Bazooka', 'Handgun', 'Knife', 'Grenade Launcher', 'Shotgun', 'SMG', 'Sniper', 'Sword']
# # anomaly_label = ['true','false']
# # anomaly_label = ['Abuse','Arrest','Arson','Assault','Burglary','Explosion','Fighting',"Normal",'RoadAccidents','Robbery','Shooting','Shoplifting','Stealing','Vandalism']
# capture_video = cv2.VideoCapture(r"C:\Users\neeli\Downloads\Knife Self Defense [You Will Get Cut].mp4") 
# # 7pne hisab se video ka path dedena wrna 0 for webcamac
# writer = None
# widht,height = None,None

# output_video_path = r"C:\Users\neeli\Downloads\output.avi"  # Specify the desired output video path
# fourcc = cv2.VideoWriter_fourcc(*"MJPG")
# output_video_writer = None
# clip_duration = 5
# frame_rate = 30  
# while True:
#     taken,frame = capture_video.read()  
#     if not taken:
#         break
#     if widht is None or height is None:
#         height,widht = frame.shape[:2]  
#     output = frame.copy()
#     frame = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
#     frame = cv2.resize(frame,(300,300)).astype("float16")
# #     frame = frame.reshape(244, 244, 3) / 255
#     frame -= mean
#     preds = model.predict(np.expand_dims(frame,axis=0))[0]
#     print(preds)
#     Queue.append(preds)
#     results = np.array(Queue).mean(axis=0)
#     i = np.argmax(results)
# #     i = (preds > 0.90)[0] #np.argmax(results)
# #     threshold = 0.5
# #     if()
#     label = anomaly_label[i]
#     print(results)
# #     i = np.argmax(results)
#     print(i)
# #     label = i
#     if(label=="Knife"):
#         if output_video_writer is None:
#             output_video_writer = cv2.VideoWriter(output_video_path, fourcc, frame_rate, (widht, height), True)
#             start_time = cv2.getTickCount() / cv2.getTickFrequency()

#         output_video_writer.write(output)
#         current_time = cv2.getTickCount() / cv2.getTickFrequency()
#         elapsed_time = (current_time - start_time) / cv2.getTickFrequency()
#         if elapsed_time >= clip_duration:
#             # Release the VideoWriter and reset variables
#             output_video_writer.release()
#             output_video_writer = None
#             print(f"Video clip saved: {output_video_path}")
#         data = im.fromarray(output) 
#         data.save('knifedummy.jpg') 

#         url = "http://ipinfo.io/json"
#         response = urlopen(url)
#         data = json.load(response)
#         print(data)
#         message = "{data}".format(data=data)
#         image =  open("knifedummy.jpg", 'rb').read() 
#         email_from = "kshitizagarwal1710@gmail.com"
#         email_to = "kshitizagarwal1710@gmail.com"
#         psw = "zzlpuafbnfcqbvfy"
#         msg = MIMEMultipart()
#         msg['Subject'] = '{label} detected'.format(label = label)
#         msg['From'] = 'kshitizagarwal1710@gmail.com'
#         msg['To'] = 'kshitizagarwal1710@gmail.com'
#         text = MIMEText(message)
#         msg.attach(text)
#         image = MIMEImage(image)
#         msg.attach(image)

#         txt = msg.as_string()

#         TIE = smtplib.SMTP(smtp_server, smtp_port) 
#         TIE.starttls()
#         TIE.login(email_from, psw)
#         print("login success")

#         print("sending mail to{email_to}")
#         TIE.sendmail(email_from, email_to, txt)
#         print("mail sent")
#         TIE.quit()
# #         print("Sending image to cloud")
# #         blob = bucket.blob("violenceDummy.jpg")
# #         blob.upload_from_filename("violenceDummy.jpg")
# #         print("image sent to cloud")
# #         message = messaging.Message(
# #             data={
# #                 'title': 'new Update ',
# #                 'body': 'Violence ereupted'
# #             },
# #             token=registration_token)
# #         # Send a message to the device corresponding to the provided
# # # registration token.
# #         response = messaging.send(message)
# # # Response is a message ID string.
# #         print('Successfully sent message:', response)

#         break
    
# #     print(label)
#     text = label
#     cv2.putText(output, text, (35, 50), cv2.FONT_HERSHEY_SIMPLEX,1.25, (255,0,0), 5)

# #     if writer is None:
# #         fourcc = cv2.VideoWriter_fourcc(*"MJPG")
# #         writer = cv2.VideoWriter(r"C:\Users\hp\Downloads\data\video_model\output\output.avi", fourcc, 30,(widht, height), True)
# #         writer.write(output)
#     cv2.imshow("Output", output)
#     if cv2.waitKey(1) & 0xFF == ord('q'):
#         break
# # print("Cleaning up...")
# # writer.release()
# # output_video_writer.release()
# # capture_video.release()
# # cv2.destroyAllWindows()
# # capture_video.release()
# if output_video_writer is not None:
#     output_video_writer.release()
# capture_video.release()
# cv2.destroyAllWindows()
# print("Video and resources cleaned up.")

anomaly_label = ['Automatic Rifle', 'Bazooka', 'Handgun', 'Knife', 'Grenade Launcher', 'Shotgun', 'SMG', 'Sniper', 'Sword']

# Create VideoWriter object to save the output video
output_video_path = r"C:\Users\neeli\Downloads\output.avi"  # Specify the desired output video path
fourcc = cv2.VideoWriter_fourcc(*"MJPG")
output_video_writer = None
clip_duration = 35
frame_rate = 30
writer = None
widht,height = None,None

# Open video capture
capture_video = cv2.VideoCapture(r"C:\Users\neeli\Downloads\Knife Self Defense [You Will Get Cut].mp4")

while True:
    taken, frame = capture_video.read()
    if not taken:
        break
    if widht is None or height is None:
        height, widht = frame.shape[:2]

    output = frame.copy()
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    frame = cv2.resize(frame, (300, 300)).astype("float16")
    #     frame = frame.reshape(244, 244, 3) / 255
    frame -= mean
    preds = model.predict(np.expand_dims(frame, axis=0))[0]
    print(preds)
    Queue.append(preds)
    results = np.array(Queue).mean(axis=0)
    i = np.argmax(results)
    label = anomaly_label[i]
    print(results)
    print(i)

    if label == "Knife":
        if output_video_writer is None:
            output_video_writer = cv2.VideoWriter(output_video_path, fourcc, frame_rate, (widht, height), True)
            start_time = time.time()

        output_video_writer.write(output)
        current_time = time.time()
        elapsed_time = current_time - start_time
        if elapsed_time >= clip_duration:
             # Release the VideoWriter and reset variables
            output_video_writer.release()
            output_video_writer = None
            print(f"Video clip saved: {output_video_path}")
            data = im.fromarray(output)
            data.save('knifedummy.jpg')

            url = "http://ipinfo.io/json"
            response = urlopen(url)
            data = json.load(response)
            print(data)
            message = "{data}".format(data=data)
            image = open("knifedummy.jpg", 'rb').read()
            email_from = "kshitizagarwal1710@gmail.com"
            email_to = "kshitizagarwal1710@gmail.com"
            psw = "zzlpuafbnfcqbvfy"
            msg = MIMEMultipart()
            msg['Subject'] = '{label} detected'.format(label=label)
            msg['From'] = 'kshitizagarwal1710@gmail.com'
            msg['To'] = 'kshitizagarwal1710@gmail.com'
            text = MIMEText(message)
            msg.attach(text)
            image = MIMEImage(image)
            msg.attach(image)

            txt = msg.as_string()

            TIE = smtplib.SMTP(smtp_server, smtp_port)
            TIE.starttls()
            TIE.login(email_from, psw)
            print("login success")

            print(f"sending mail to {email_to}")
            TIE.sendmail(email_from, email_to, txt)
            print("mail sent")
            TIE.quit()
            print("Sending video to cloud")
            blob = bucket.blob("output.avi")
            blob.upload_from_filename(r"C:\Users\neeli\Downloads\output.avi")
            print("video sent to cloud")


            break

    text = label
    cv2.putText(output, text, (35, 50), cv2.FONT_HERSHEY_SIMPLEX, 1.25, (255, 0, 0), 5)

    cv2.imshow("Output", output)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the VideoWriter and other resources
if output_video_writer is not None:
    output_video_writer.release()
capture_video.release()
cv2.destroyAllWindows()

print("Video and resources cleaned up.")

1/1 [==============================] - 0s 220ms/step
[[5.2238995e-01 1.0487247e-04 7.1286702e-01 9.2464828e-01]]
[[0.49840593 0.00606759 0.6336346  0.862533  ]]
3
1/1 [==============================] - 0s 234ms/step
[[5.2280271e-01 1.0531351e-04 7.1264613e-01 9.2441756e-01]]
[[0.49864516 0.00600914 0.6344092  0.8631396 ]]
3
1/1 [==============================] - 0s 218ms/step
[[5.1762825e-01 2.7358887e-04 4.9847302e-01 8.4717196e-01]]
[[0.49882945 0.00595346 0.6330895  0.86298466]]
3
1/1 [==============================] - 0s 226ms/step
[[5.3347033e-01 2.2252538e-04 5.0259328e-01 8.5550183e-01]]
[[0.49916252 0.00589835 0.6318347  0.8629127 ]]
3
1/1 [==============================] - 0s 176ms/step
[[5.4177052e-01 1.9665479e-04 5.5769432e-01 8.3385777e-01]]
[[0.4995683  0.00584405 0.6311286  0.86263597]]
3
1/1 [==============================] - 0s 205ms/step
[[5.8678359e-01 2.8720958e-04 4.7093949e-01 7.7537340e-01]]
[[0.5003911  0.00579163 0.6296174  0.8618127 ]]
3
1/1 [=================

1/1 [==============================] - 0s 166ms/step
[[0.38498908 0.00275013 0.8465256  0.8904981 ]]
[[0.4899801  0.00824972 0.6362072  0.8324217 ]]
3
1/1 [==============================] - 0s 189ms/step
[[0.38279653 0.00115597 0.8329916  0.93516016]]
[[0.4898561  0.00814658 0.6373104  0.83407855]]
3
1/1 [==============================] - 0s 182ms/step
[[0.4896833  0.00154081 0.79260856 0.82012343]]
[[0.49048373 0.00805125 0.6375218  0.834634  ]]
3
1/1 [==============================] - 0s 199ms/step
[[0.5018874  0.00100921 0.6989594  0.9784932 ]]
[[0.4908181  0.00790523 0.6381292  0.8370176 ]]
3
1/1 [==============================] - 0s 201ms/step
[[6.0454232e-01 4.9854134e-04 8.1460232e-01 9.5254582e-01]]
[[0.49191427 0.00734319 0.6398694  0.84030354]]
3
1/1 [==============================] - 0s 193ms/step
[[6.3484240e-01 3.1705684e-04 8.7035644e-01 9.7027278e-01]]
[[0.49264312 0.00707847 0.6429316  0.84445745]]
3
1/1 [==============================] - 0s 191ms/step
[[5.0634062e-01 1